image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1805.46663,    0.     ,  720.56741,
            0.     , 1803.59436,  569.74359,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.085519, 0.158128, 0.001561, -0.000446, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1788.07452,    0.     ,  720.18131,    0.     ,
            0.     , 1791.59618,  570.83055,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
